services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: user-management-php
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./app/database:/var/www/database
    expose:
      - 9000
    command: >
      sh -c "[ -d storage ] && chmod -R 777 storage || echo 'skip'; [ -d bootstrap/cache ] && chmod -R 777 bootstrap/cache || echo 'skip'; [ -d database ] && chmod -R 777 database || echo 'skip'; php-fpm"


  nginx:
    image: nginx:latest
    container_name: user-management-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
